//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csharpProject_gestionStock.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture
    {
        public int Id { get; set; }
        public string CodeProduit { get; set; }
        public string NomClient { get; set; }
        public string PrenomClient { get; set; }
        public string TelephoneClient { get; set; }
        public Nullable<int> Quantite { get; set; }
        public Nullable<int> Prix { get; set; }
        public Nullable<int> Total { get; set; }
        public string IdentifiantUtilisateur { get; set; }
        public Nullable<System.DateTime> dateVente { get; set; }
    }
}
