//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csharpProject_gestionStock.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BdKireneEntities : DbContext
    {
        public BdKireneEntities()
            : base("name=BdKireneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<Produit> Produit { get; set; }
        public virtual DbSet<Approvisionnement> Approvisionnement { get; set; }
        public virtual DbSet<Profil> Profil { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
        public virtual DbSet<Facture> Facture { get; set; }
        public virtual DbSet<VRechercheProduit> VRechercheProduit { get; set; }
    }
}
